### ISSUE TITLE
Mac SDK 6.2 broke qcr startup script

### ISSUE THREAD

**Issue by curtislisle** [XDATA-Year-3/QCR-mentions-prototype#14]
Apple helpfully updated my Xcode version last night without asking me.  Now the qcr startup app doesn't work anymore.  Tangelo fails 

./qcr
error reading configuration file /Users/clisle/code/qcr/QCR-mentions-prototype/tangelo-config.yaml: No JSON object could be decoded

This is after replacing "readlink" in line 38, with "stat" because readlink changed in the Mac SDK

**Comment by curtislisle** [comment]
Nevermind.  The SDK did change, but I had forgotten to run under a special tangelo09 python virtualenv

**Comment by ronichoudhury** [comment]
Oh, whew!  I was starting to get worried about what this could mean... glad you got it fixed!
