### ISSUE TITLE
Configure initial central tweeter

### ISSUE THREAD

**Issue by ronichoudhury** [XDATA-Year-3/QCR-mentions-prototype#6]

**Comment by curtislisle** [comment]
Use a configuration file for Mentions app to allow central tweeter and mongo collection to be set without hard-coded name changes anymore.

**Comment by curtislisle** [comment]
Commit in branch "defaults" resolves this.  defaults.json is scanned for date, centralEntity, and collection name to use. We could expand on this later to provide a routine to reinitialize by setting the global variables from a JSON object on demand.  This is not needed right away.

**Comment by ronichoudhury** [comment]
Closed via #11
